name: Deploy

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest

    steps:
      - name: Checkout backend
        uses: actions/checkout@v4

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Log in to Heroku Container Registry
        run: echo "${{ secrets.HEROKU_API_KEY }}" | docker login --username="${{ secrets.HEROKU_EMAIL }}" --password-stdin registry.heroku.com

      - name: Build Docker image
        run: docker build -t registry.heroku.com/${{ vars.HEROKU_BE_APP_NAME }}/web .

      - name: Push Docker image to Heroku
        run: docker push registry.heroku.com/${{ vars.HEROKU_BE_APP_NAME }}/web

      - name: Release image on Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release web --app "${{ vars.HEROKU_BE_APP_NAME }}"
